# Generated by Django 3.1.3 on 2020-11-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gitlink',
            field=models.CharField(default='www.google.com', max_length=400),
            preserve_default=False,
        ),
    ]
